version: '2'

services:
  redis:
    image: redis
    command: redis-server --appendonly yes
    hostname: redis
    ports:
      - "6379:6379" # Note: you should not expose this port in production environments
    volumes:
      - /data

  mosquitto:
    image: eclipse-mosquitto
    restart: always
    mem_limit: 64m
    ports:
      - "1883:1883"
    environment:
      MQTTNAUTH_CACHE_HOST: redis

  discovery:
    image: thethingsnetwork/ttn:latest
    command: discovery
    depends_on:
      - redis
    networks:
      default:
        aliases:
          - discovery.local.thethings.network
    ports:
      - "1900:1900"
      - "8081:8080"
    volumes:
      - "./config/discovery.yml:/root/.ttn.yml"
      - "./keys/discovery:/root/keys"

  router:
    image: thethingsnetwork/ttn:latest
    command: router
    depends_on:
      - discovery
    networks:
      default:
        aliases:
          - router.local.thethings.network
    ports:
      - "1901:1901"
    volumes:
      - "./keys/discovery/server.cert:/root/keys/ca.cert"
      - "./keys/router/server.pub:/root/keys/server.pub"
      - "./keys/router/server.key:/root/keys/server.key"
      - "./keys/router/server.cert:/root/keys/server.cert"
      - "./config/router.yml:/root/.ttn.yml"


  broker:
    image: thethingsnetwork/ttn:latest
    command: broker
    environment:
      TTN_BROKER_NETWORKSERVER_ADDRESS: networkserver:1903
    depends_on:
      - discovery
      - networkserver
    networks:
      default:
        aliases:
          - broker.local.thethings.network
    ports:
      - "1902:1902"
    volumes:
      - "./keys/discovery/server.cert:/root/keys/ca.cert"
      - "./keys/networkserver/server.cert:/root/keys/networkserver.cert"
      - "./keys/broker/server.pub:/root/keys/server.pub"
      - "./keys/broker/server.key:/root/keys/server.key"
      - "./keys/broker/server.cert:/root/keys/server.cert"
      - "./config/broker.yml:/root/.ttn.yml"

  networkserver:
    image: thethingsnetwork/ttn:latest
    command: networkserver 
    depends_on:
      - redis
    networks:
      default:
        aliases:
          - networkserver.local.thethings.network
    ports:
      - "1903:1903" # Note: you should not expose this port in production environments
    volumes:
      - "./config/networkserver.yml:/root/.ttn.yml"
      - "./keys/networkserver:/root/keys"

  handler:
    image: thethingsnetwork/ttn:latest
    command: handler
    depends_on:
      - discovery
      - redis
      - mosquitto
    networks:
      default:
        aliases:
          - handler.local.thethings.network
    ports:
      - "1904:1904"
      - "8084:8084"
    volumes:
      - "./keys/discovery/server.cert:/root/keys/ca.cert"
      - "./keys/handler/server.pub:/root/keys/server.pub"
      - "./keys/handler/server.key:/root/keys/server.key"
      - "./keys/handler/server.cert:/root/keys/server.cert"
      - "./config/handler.yml:/root/.ttn.yml"

  bridge:
    image: thethingsnetwork/gateway-connector-bridge:latest
    depends_on:
      - router
    environment:
      BRIDGE_REDIS_ADDRESS: redis:6379
      BRIDGE_UDP: :1700
    ports:
      - "1700:1700/udp"
    env_file: config/bridge.env
    volumes:
     - "./keys/discovery/server.cert:/root/keys/ca.cert"
    networks:
      default:

